services:
  groweasy-api:
    image: arackrs/groweasyiot
    container_name: groweasyiot-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:groweasy;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      SPRING_DATASOURCE_USERNAME: arack
      SPRING_DATASOURCE_PASSWORD: 123
      JWT_SECRET_KEY: 8ebc070bb4a53120cd451cf58f4f48067decc4077a4b8d1f2a6632305cc4c299
      JWT_USER_GENERATOR: AUTH0JWT
    networks:
      - internalnet

networks:
  internalnet: