#server:
#  port: 8080
#
#spring:
#  application:
#    name: GROWEASY
#  datasource:
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#    driver-class-name: org.h2.Driver

server:
  port: 8080

spring:
  application:
    name: GROWEASY
  datasource:
    url: jdbc:mysql://databasems.mysql.database.azure.com/groweasydb?useSSL=true&serverTimezone=UTC
    username: arack
    password: jarraj*160104
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: false

jwt:
  secret:
    key: 8ebc070bb4a53120cd451cf58f4f48067decc4077a4b8d1f2a6632305cc4c299
  user:
    generator: AUTH0JWT_ARACK
